# Generated by Django 5.2.9 on 2026-01-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_add_tag_color_description_isactive"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_jti", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "refresh_token_jti",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Token",
                "verbose_name_plural": "Session Tokens",
                "db_table": "session_token",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["user", "is_active"], name="session_tok_user_id_5efc58_idx"),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["token_jti"], name="session_tok_token_jti_6a59d0_idx"),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["expires_at"], name="session_tok_expires_6e245c_idx"),
        ),
    ]
